In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("Student Social Media And Mental Health Impact.csv")

In [4]:
df.head()

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
0,21,Male,Other,Undergraduate,Facebook,Networking,4.0,134,4.5,2.2,6.7,Medium,6.8
1,23,Female,Other,Graduate,LinkedIn,Education,1.6,73,7.0,2.4,8.6,Low,7.6
2,22,Male,Canada,Undergraduate,Instagram,Entertainment,4.6,166,4.0,1.8,6.7,Medium,7.0
3,18,Male,Other,High School,Snapchat,Entertainment,7.0,220,1.0,1.7,5.4,Very High,5.3
4,24,Female,Other,Graduate,Facebook,Networking,7.5,237,1.0,1.1,5.0,Very High,4.4

In [5]:
df.shape

(5000, 13)

In [6]:
df.isnull().sum()

Age                        0
Gender                     0
Country                    0
Academic_Level             0
Most_Used_Platform         0
Purpose_Of_Use             0
Avg_Daily_Usage_Hours      0
Daily_Unlocks              0
Study_Hours                0
Physical_Activity_Hours    0
Sleep_Hours_Per_Night      0
Stress_Level               0
Mental_Health_Score        0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      5000 non-null   int64
 1   Gender                   5000 non-null   object
 2   Country                  5000 non-null   object
 3   Academic_Level           5000 non-null   object
 4   Most_Used_Platform       5000 non-null   object
 5   Purpose_Of_Use           5000 non-null   object
 6   Avg_Daily_Usage_Hours    5000 non-null   float64
 7   Daily_Unlocks            5000 non-null   int64
 8   Study_Hours              5000 non-null   float64
 9   Physical_Activity_Hours  5000 non-null   float64
 10  Sleep_Hours_Per_Night    5000 non-null   float64
 11  Stress_Level             5000 non-null   object
 12  Mental_Health_Score      5000 non-null   float64
dtypes: float64(5), int64(2), object(6)
memory usage: 507.9+ KB

In [8]:
df.duplicated().sum()

np.int64(2)

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(4998, 13)

In [11]:
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000
mean,20.822129,5.078491,171.455582,3.008403,1.750760,6.634654,6.231152
std,1.736774,1.654097,42.859829,1.636831,0.668406,1.221561,1.278476
min,18.000000,1.000000,62.000000,0.300000,-0.400000,3.600000,3.600000
25%,19.000000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.000000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.000000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.000000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [12]:
df['Physical_Activity_Hours'] = df['Physical_Activity_Hours'].clip(lower=0)

In [13]:
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000,4998.000000
mean,20.822129,5.078491,171.455582,3.008403,1.751160,6.634654,6.231152
std,1.736774,1.654097,42.859829,1.636831,0.667282,1.221561,1.278476
min,18.000000,1.000000,62.000000,0.300000,0.000000,3.600000,3.600000
25%,19.000000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.000000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.000000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.000000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [14]:
num_cols = df.select_dtypes(include='number')
num_cols.skew()

Age                        0.155008
Avg_Daily_Usage_Hours      0.005575
Daily_Unlocks              0.002309
Study_Hours                0.436125
Physical_Activity_Hours    0.053288
Sleep_Hours_Per_Night      0.123919
Mental_Health_Score        0.207086
dtype: float64

In [15]:
df.columns

Index(['Age', 'Gender', 'Country', 'Academic_Level', 'Most_Used_Platform',
       'Purpose_Of_Use', 'Avg_Daily_Usage_Hours', 'Daily_Unlocks',
       'Study_Hours', 'Physical_Activity_Hours', 'Sleep_Hours_Per_Night',
       'Stress_Level', 'Mental_Health_Score'],
      dtype='object')

In [16]:
ord_col = df.select_dtypes(include='object')
ord_col['Country'].nunique()

111

In [17]:
counts = df['Country'].value_counts()

threshold = 100 

repl = counts[counts<=threshold].index

df['Country'] = df['Country'].replace(repl,'Other')

In [18]:
Q1 = num_cols.quantile(0.25)

Q3 = num_cols.quantile(0.75)

IQR =  Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = (num_cols < lower_limit) | (num_cols > upper_limit)
outliers.sum()

Age                         0
Avg_Daily_Usage_Hours       0
Daily_Unlocks               0
Study_Hours                 2
Physical_Activity_Hours    12
Sleep_Hours_Per_Night       0
Mental_Health_Score         0
dtype: int64

In [19]:
df = df[(df['Study_Hours'] < upper_limit['Study_Hours']) & (df['Study_Hours'] > lower_limit['Study_Hours'])]

In [20]:
df = df[(df['Physical_Activity_Hours'] < upper_limit['Physical_Activity_Hours']) & (df['Physical_Activity_Hours'] > lower_limit['Physical_Activity_Hours'])]

In [21]:
df.shape

(4984, 13)

In [22]:
skew_col = ['Study_Hours']

numeric_cols = ['Age','Avg_Daily_Usage_Hours','Daily_Unlocks','Physical_Activity_Hours','Sleep_Hours_Per_Night']

ordinal_cols = ['Academic_Level','Stress_Level']

nominal_cols = ['Gender','Country','Most_Used_Platform','Purpose_Of_Use']

features = skew_col + numeric_cols + ordinal_cols + nominal_cols
x = df[features]
y = df['Mental_Health_Score']

In [23]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [26]:
from sklearn.preprocessing import StandardScaler, FunctionTransformer, OrdinalEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

study_hours_pipeline = Pipeline(steps=[
    ('log_transform', FunctionTransformer(np.log1p)),
    ('scaler', StandardScaler())
])

preprocessing = ColumnTransformer(transformers=[
    ('study_hours', study_hours_pipeline, skew_col),
    ('numer',StandardScaler(),numeric_cols),
    ('ordinal',OrdinalEncoder(categories=[['High School', 'Undergraduate', 'Graduate'],['Low', 'Medium', 'High', 'Very High']]),ordinal_cols),
    ('nominal',OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32),nominal_cols)
])

In [27]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

rf_pipeline = Pipeline(steps=[
                       ('preprocessing',preprocessing),
                       ('regression',RandomForestRegressor())
])

In [28]:
rf_pipeline.fit(x_train, y_train)

rf_pred_test = rf_pipeline.predict(x_test)
rf_pred_train = rf_pipeline.predict(x_train)

testing_accuracy = r2_score(y_test,rf_pred_test)
traning_accuracy = r2_score(y_train,rf_pred_train)
mae_score = mean_absolute_error(y_test, rf_pred_test)

print(f"Accuracy of Training {traning_accuracy}")
print(f"Accuracy of Testing {testing_accuracy}")
print(f'MAE {mae_score}')

Accuracy of Training 0.9828296977392414
Accuracy of Testing 0.8835877857890375
MAE 0.32324998328318305

In [29]:
# cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(rf_pipeline, x_train, y_train, cv=5, scoring='r2').mean()

np.float64(0.8628331439940988)

In [30]:
param_grid = {
    'regression__n_estimators': [20, 50, 100, 150, 200],
    'regression__max_features': [0.25, 0.5, 0.75, 1.0],
    'regression__max_depth': [None, 2, 6, 10],
    'regression__max_samples': [0.5, 0.7, 0.8, 1.0]
}

In [192]:
from sklearn.model_selection import GridSearchCV

rf_grid = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring='r2',
    verbose=2,
    n_jobs=-1
)

In [193]:
rf_grid.fit(x_train, y_train)

Fitting 5 folds for each of 320 candidates, totalling 1600 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessing',
                                        ColumnTransformer(transformers=[('study_hours',
                                                                         Pipeline(steps=[('log_transform',
                                                                                          FunctionTransformer(func=<ufunc 'log1p'>)),
                                                                                         ('scaler',
                                                                                          StandardScaler())]),
                                                                         ['Study_Hours']),
                                                                        ('numer',
                                                                         StandardScaler(),
                                                                         ['Age',
                                                                          'Avg_Daily_Usage_Hours',
                                                                          'Daily_Unlocks',
                                                                          'Physical_Activity_Hours',
                                                                          'Sleep_Hours_Per_Nigh...
                                                                                       dtype=<class 'numpy.int32'>,
                                                                                       sparse_output=False),
                                                                         ['Gender',
                                                                          'Country',
                                                                          'Most_Used_Platform',
                                                                          'Purpose_Of_Use'])])),
                                       ('regression',
                                        RandomForestRegressor())]),
             n_jobs=-1,
             param_grid={'regression__max_depth': [None, 2, 6, 10],
                         'regression__max_features': [0.25, 0.5, 0.75, 1.0],
                         'regression__max_samples': [0.5, 0.7, 0.8, 1.0],
                         'regression__n_estimators': [20, 50, 100, 150, 200]},
             scoring='r2', verbose=2)

In [194]:
print("Best parameters:", rf_grid.best_params_)
print("Best CV R² score:", rf_grid.best_score_)

Best parameters: {'regression__max_depth': None, 'regression__max_features': 0.25, 'regression__max_samples': 1.0, 'regression__n_estimators': 200}
Best CV R² score: 0.8712142115244005

In [195]:
best_rf_model = rf_grid.best_estimator_

rf_pred_train = best_rf_model.predict(x_train)
rf_pred_test = best_rf_model.predict(x_test)

training_r2 = r2_score(y_train, rf_pred_train)
testing_r2 = r2_score(y_test, rf_pred_test)
mae = mean_absolute_error(y_test, rf_pred_test)

print(f"Training R²: {training_r2:.4f}")
print(f"Testing R²: {testing_r2:.4f}")
print(f"MAE: {mae:.4f}")

Training R²: 0.9847
Testing R²: 0.8927
MAE: 0.3134

In [231]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.linear_model import LinearRegression

def objective(trial):

    regressor_name = trial.suggest_categorical('regressor', ['GradientBoostingRegressor','SVR','LinearRegression','RandomForest','XGBoost'])

    if regressor_name == 'SVR':
        c = trial.suggest_float('c', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear','rbf','poly','sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale','auto'])

        model = SVR(C=c, kernel=kernel, gamma=gamma)


    elif regressor_name == 'LinearRegression':
        model = LinearRegression()


    elif regressor_name == 'GradientBoostingRegressor':
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingRegressor(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )


    elif regressor_name == 'RandomForest':
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestRegressor(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )


    elif regressor_name == 'XGBoost':
        n_estimators = trial.suggest_int('n_estimators',50,500)
        learning_rate = trial.suggest_float('learning_rate',0.01,0.3,log=True)
        max_depth = trial.suggest_int('max_depth',2,12)
        min_child_weight = trial.suggest_int('min_child_weight',1,10)
        subsample = trial.suggest_float('subsample',0.5,1.0)
        colsample_bytree = trial.suggest_float('colsample_bytree',0.5,1.0)
        reg_alpha = trial.suggest_float('reg_alpha',1e-8,10.0,log=True)
        reg_lambda = trial.suggest_float('reg_lambda',1e-8,10.0,log=True)

        model = XGBRegressor(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_child_weight=min_child_weight,
            subsample=subsample,
            colsample_bytree=colsample_bytree,
            reg_alpha=reg_alpha,
            reg_lambda=reg_lambda,
            objective='reg:squarederror',
            random_state=42,
            n_jobs=-1
        )


    model_pipeline = Pipeline(steps=[
        ('preprocessing', preprocessing),
        ('regression', model)
     ])


    score =cross_val_score(model_pipeline, x_train, y_train, cv=3, scoring='r2', n_jobs=-1, error_score='raise').mean()
    return score

In [232]:
import optuna

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-07-25 12:06:38,739] A new study created in memory with name: no-name-86f9be14-7c10-453c-a51d-856660237185
[I 2026-07-25 12:06:42,057] Trial 0 finished with value: 0.7224788149803625 and parameters: {'regressor': 'LinearRegression'}. Best is trial 0 with value: 0.7224788149803625.
[I 2026-07-25 12:06:45,333] Trial 1 finished with value: -846.0060152626188 and parameters: {'regressor': 'SVR', 'c': 0.7182413024388615, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7224788149803625.
[I 2026-07-25 12:06:48,187] Trial 2 finished with value: -1360.352997699579 and parameters: {'regressor': 'SVR', 'c': 0.9112253688026797, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 0 with value: 0.7224788149803625.
[I 2026-07-25 12:06:54,312] Trial 3 finished with value: 0.7747820680709961 and parameters: {'regressor': 'RandomForest', 'n_estimators': 196, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 3 with value: 0.7747820680709961.
[I 2026-07-25 12:06:55,587] Trial 4 finished with value: 0.7208708190228522 and parameters: {'regressor': 'SVR', 'c': 0.15860358998328716, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7747820680709961.
[I 2026-07-25 12:07:15,287] Trial 5 finished with value: 0.7206507106466971 and parameters: {'regressor': 'SVR', 'c': 26.37576040839569, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7747820680709961.
[I 2026-07-25 12:07:24,007] Trial 6 finished with value: 0.7669422103545767 and parameters: {'regressor': 'SVR', 'c': 22.261591533289973, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 3 with value: 0.7747820680709961.
[I 2026-07-25 12:07:26,996] Trial 7 finished with value: 0.8475913512149663 and parameters: {'regressor': 'GradientBoostingRegressor', 'n_estimators': 81, 'learning_rate': 0.046107430003527725, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 4}. Best is trial 7 with value: 0.8475913512149663.
[I 2026-07-25 12:07:38,989] Trial 8 finished with value: 0.7652700974334937 and parameters: {'regressor': 'GradientBoostingRegressor', 'n_estimators': 221, 'learning_rate': 0.025391402345272568, 'max_depth': 19, 'min_samples_split': 2, 'min_samples_leaf': 1}. Best is trial 7 with value: 0.8475913512149663.
[I 2026-07-25 12:07:39,999] Trial 9 finished with value: 0.8500600179686381 and parameters: {'regressor': 'XGBoost', 'n_estimators': 255, 'learning_rate': 0.07726566637031751, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.5585025296033301, 'colsample_bytree': 0.5800692538649934, 'reg_alpha': 2.314078300602422e-06, 'reg_lambda': 0.08136041051706093}. Best is trial 9 with value: 0.8500600179686381.
[I 2026-07-25 12:07:41,036] Trial 10 finished with value: 0.8200401826327942 and parameters: {'regressor': 'XGBoost', 'n_estimators': 474, 'learning_rate': 0.2532781490337975, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.52863964863963, 'colsample_bytree': 0.5529962218650101, 'reg_alpha': 1.2047702339558174e-06, 'reg_lambda': 0.23518956119562667}. Best is trial 9 with value: 0.8500600179686381.
[I 2026-07-25 12:07:42,756] Trial 11 finished with value: 0.84383681767228 and parameters: {'regressor': 'GradientBoostingRegressor', 'n_estimators': 52, 'learning_rate': 0.08046233914026218, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 9 with value: 0.8500600179686381.
[I 2026-07-25 12:07:43,330] Trial 12 finished with value: 0.8424912852387075 and parameters: {'regressor': 'XGBoost', 'n_estimators': 55, 'learning_rate': 0.057722330853856946, 'max_depth': 11, 'min_child_weight': 4, 'subsample': 0.6444358701194407, 'colsample_bytree': 0.6626224818579163, 'reg_alpha': 0.007147894575783735, 'reg_lambda': 3.247077140810769e-06}. Best is trial 9 with value: 0.8500600179686381.
[I 2026-07-25 12:07:44,474] Trial 13 finished with value: 0.8521934276371418 and parameters: {'regressor': 'XGBoost', 'n_estimators': 369, 'learning_rate': 0.08877592376221205, 'max_depth': 7, 'min_child_weight': 10, 'subsample': 0.9654116085526498, 'colsample_bytree': 0.9796052896777518, 'reg_alpha': 2.5333182353447994e-08, 'reg_lambda': 3.6656440563185844}. Best is trial 13 with value: 0.8521934276371418.
[I 2026-07-25 12:07:45,480] Trial 14 finished with value: 0.8496596913003861 and parameters: {'regressor': 'XGBoost', 'n_estimators': 375, 'learning_rate': 0.14815816558366776, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.9620030605480817, 'colsample_bytree': 0.999886504939791, 'reg_alpha': 3.7951732829336565e-08, 'reg_lambda': 9.683818068497336}. Best is trial 13 with value: 0.8521934276371418.
[I 2026-07-25 12:07:46,261] Trial 15 finished with value: 0.8552179898612072 and parameters: {'regressor': 'XGBoost', 'n_estimators': 331, 'learning_rate': 0.10070385764034594, 'max_depth': 7, 'min_child_weight': 10, 'subsample': 0.9018801440667295, 'colsample_bytree': 0.9321008705360679, 'reg_alpha': 1.7888426447078807e-06, 'reg_lambda': 0.05186039053672946}. Best is trial 15 with value: 0.8552179898612072.
[I 2026-07-25 12:07:47,132] Trial 16 finished with value: 0.8153073890181886 and parameters: {'regressor': 'XGBoost', 'n_estimators': 364, 'learning_rate': 0.011237217072606394, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.9575213771807182, 'colsample_bytree': 0.9415329488160861, 'reg_alpha': 1.3084725372056639e-08, 'reg_lambda': 0.002007228889047799}. Best is trial 15 with value: 0.8552179898612072.
[I 2026-07-25 12:07:47,244] Trial 17 finished with value: 0.7224788149803625 and parameters: {'regressor': 'LinearRegression'}. Best is trial 15 with value: 0.8552179898612072.
[I 2026-07-25 12:07:52,627] Trial 18 finished with value: 0.8032736352877924 and parameters: {'regressor': 'RandomForest', 'n_estimators': 299, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 15 with value: 0.8552179898612072.
[I 2026-07-25 12:07:53,401] Trial 19 finished with value: 0.7891415453189019 and parameters: {'regressor': 'XGBoost', 'n_estimators': 450, 'learning_rate': 0.13705307897055513, 'max_depth': 2, 'min_child_weight': 1, 'subsample': 0.83989437517614, 'colsample_bytree': 0.8480857490823243, 'reg_alpha': 6.166000444276165e-05, 'reg_lambda': 6.070450717164715}. Best is trial 15 with value: 0.8552179898612072.
[I 2026-07-25 12:07:54,358] Trial 20 finished with value: 0.826557387951722 and parameters: {'regressor': 'XGBoost', 'n_estimators': 349, 'learning_rate': 0.1453942082813162, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.82826769729064, 'colsample_bytree': 0.8419491673379125, 'reg_alpha': 4.860115825652705, 'reg_lambda': 0.0018244907331988914}. Best is trial 15 with value: 0.8552179898612072.
[I 2026-07-25 12:07:55,348] Trial 21 finished with value: 0.8539303438643334 and parameters: {'regressor': 'XGBoost', 'n_estimators': 255, 'learning_rate': 0.08661758721997138, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.9948678705208005, 'colsample_bytree': 0.6681429063274634, 'reg_alpha': 3.460983474866397e-06, 'reg_lambda': 0.06620833867956212}. Best is trial 15 with value: 0.8552179898612072.
[I 2026-07-25 12:07:56,416] Trial 22 finished with value: 0.8580225351089439 and parameters: {'regressor': 'XGBoost', 'n_estimators': 307, 'learning_rate': 0.09966443688773477, 'max_depth': 8, 'min_child_weight': 8, 'subsample': 0.9856444290958077, 'colsample_bytree': 0.7110187067166781, 'reg_alpha': 1.6818386886353538e-06, 'reg_lambda': 0.06650736864021028}. Best is trial 22 with value: 0.8580225351089439.
[I 2026-07-25 12:07:57,838] Trial 23 finished with value: 0.858052694201438 and parameters: {'regressor': 'XGBoost', 'n_estimators': 298, 'learning_rate': 0.037256734464431736, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.8754319873748782, 'colsample_bytree': 0.7184118120422995, 'reg_alpha': 1.2693072944418626e-05, 'reg_lambda': 0.032191672035283024}. Best is trial 23 with value: 0.858052694201438.
[I 2026-07-25 12:07:59,359] Trial 24 finished with value: 0.8529033598681388 and parameters: {'regressor': 'XGBoost', 'n_estimators': 311, 'learning_rate': 0.028716065355306127, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.85426777288357, 'colsample_bytree': 0.7590637141570492, 'reg_alpha': 0.00024332701165482126, 'reg_lambda': 5.5898820723041455e-05}. Best is trial 23 with value: 0.858052694201438.
[I 2026-07-25 12:08:00,325] Trial 25 finished with value: 0.8480053339613433 and parameters: {'regressor': 'XGBoost', 'n_estimators': 145, 'learning_rate': 0.026249786047404057, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.8840183816003001, 'colsample_bytree': 0.7272146517021795, 'reg_alpha': 1.1690479329843949e-05, 'reg_lambda': 1.381376767410045e-08}. Best is trial 23 with value: 0.858052694201438.
[I 2026-07-25 12:08:00,488] Trial 26 finished with value: 0.7224788149803625 and parameters: {'regressor': 'LinearRegression'}. Best is trial 23 with value: 0.858052694201438.
[I 2026-07-25 12:08:08,289] Trial 27 finished with value: 0.7604011429805243 and parameters: {'regressor': 'RandomForest', 'n_estimators': 267, 'max_depth': 14, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 23 with value: 0.858052694201438.
[I 2026-07-25 12:08:09,610] Trial 28 finished with value: 0.8491784170565858 and parameters: {'regressor': 'XGBoost', 'n_estimators': 418, 'learning_rate': 0.039390352440754346, 'max_depth': 7, 'min_child_weight': 8, 'subsample': 0.7550979768352252, 'colsample_bytree': 0.7677352579735035, 'reg_alpha': 0.0029269968533395703, 'reg_lambda': 0.01128953879207444}. Best is trial 23 with value: 0.858052694201438.
[I 2026-07-25 12:08:09,739] Trial 29 finished with value: 0.7224788149803625 and parameters: {'regressor': 'LinearRegression'}. Best is trial 23 with value: 0.858052694201438.
[I 2026-07-25 12:08:11,140] Trial 30 finished with value: 0.8390482368603861 and parameters: {'regressor': 'XGBoost', 'n_estimators': 332, 'learning_rate': 0.014762450773078055, 'max_depth': 8, 'min_child_weight': 8, 'subsample': 0.913600874806773, 'colsample_bytree': 0.6738430803171837, 'reg_alpha': 3.845034031485894e-07, 'reg_lambda': 0.00011101855269735383}. Best is trial 23 with value: 0.858052694201438.
[I 2026-07-25 12:08:11,978] Trial 31 finished with value: 0.8603679167948166 and parameters: {'regressor': 'XGBoost', 'n_estimators': 232, 'learning_rate': 0.11636517618383738, 'max_depth': 8, 'min_child_weight': 6, 'subsample': 0.9906157408786256, 'colsample_bytree': 0.6706947140112752, 'reg_alpha': 1.1416550951704263e-05, 'reg_lambda': 0.11678836698289066}. Best is trial 31 with value: 0.8603679167948166.
[I 2026-07-25 12:08:13,026] Trial 32 finished with value: 0.8670140383070929 and parameters: {'regressor': 'XGBoost', 'n_estimators': 191, 'learning_rate': 0.12195322260904184, 'max_depth': 10, 'min_child_weight': 5, 'subsample': 0.911780807204017, 'colsample_bytree': 0.6095543020128379, 'reg_alpha': 3.357206549075141e-05, 'reg_lambda': 0.3950658131485099}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:13,985] Trial 33 finished with value: 0.8608258653952711 and parameters: {'regressor': 'XGBoost', 'n_estimators': 187, 'learning_rate': 0.24370482230393367, 'max_depth': 10, 'min_child_weight': 5, 'subsample': 0.9876505886640022, 'colsample_bytree': 0.6173313642644915, 'reg_alpha': 4.356314371937553e-05, 'reg_lambda': 0.5890947205038907}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:14,972] Trial 34 finished with value: 0.8595516041548668 and parameters: {'regressor': 'XGBoost', 'n_estimators': 162, 'learning_rate': 0.20669963289584817, 'max_depth': 10, 'min_child_weight': 4, 'subsample': 0.7748404077817863, 'colsample_bytree': 0.6052707564179567, 'reg_alpha': 5.9075408198684875e-05, 'reg_lambda': 0.7523469431805271}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:18,037] Trial 35 finished with value: 0.8094559270566063 and parameters: {'regressor': 'RandomForest', 'n_estimators': 155, 'max_depth': 13, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:18,776] Trial 36 finished with value: 0.8499245306145209 and parameters: {'regressor': 'XGBoost', 'n_estimators': 158, 'learning_rate': 0.2965703829805115, 'max_depth': 10, 'min_child_weight': 4, 'subsample': 0.7209838398474622, 'colsample_bytree': 0.6030736107737721, 'reg_alpha': 0.0006350086013804574, 'reg_lambda': 1.02285933260954}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:42,596] Trial 37 finished with value: 0.7916218723850058 and parameters: {'regressor': 'SVR', 'c': 66.08686166308178, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:49,517] Trial 38 finished with value: 0.8478246854885162 and parameters: {'regressor': 'GradientBoostingRegressor', 'n_estimators': 188, 'learning_rate': 0.21926828733910728, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 3}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:49,614] Trial 39 finished with value: 0.7224788149803625 and parameters: {'regressor': 'LinearRegression'}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:50,422] Trial 40 finished with value: 0.749417261789274 and parameters: {'regressor': 'SVR', 'c': 5.247713530344947, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:51,023] Trial 41 finished with value: 0.8529332078348967 and parameters: {'regressor': 'XGBoost', 'n_estimators': 117, 'learning_rate': 0.18835680651610778, 'max_depth': 10, 'min_child_weight': 5, 'subsample': 0.782850272971601, 'colsample_bytree': 0.6200973880070968, 'reg_alpha': 3.551116542583794e-05, 'reg_lambda': 0.5336095591395963}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:52,069] Trial 42 finished with value: 0.8619908132440441 and parameters: {'regressor': 'XGBoost', 'n_estimators': 227, 'learning_rate': 0.1766008255791077, 'max_depth': 10, 'min_child_weight': 3, 'subsample': 0.9249573491671043, 'colsample_bytree': 0.5229889018753956, 'reg_alpha': 6.988802660524055e-05, 'reg_lambda': 0.8515063772099043}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:52,959] Trial 43 finished with value: 0.8642843876397884 and parameters: {'regressor': 'XGBoost', 'n_estimators': 212, 'learning_rate': 0.17796060254079363, 'max_depth': 10, 'min_child_weight': 3, 'subsample': 0.9288391761446945, 'colsample_bytree': 0.5006898903185826, 'reg_alpha': 0.00018946391076702436, 'reg_lambda': 1.1017635324580355}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:54,317] Trial 44 finished with value: 0.8647910217345859 and parameters: {'regressor': 'XGBoost', 'n_estimators': 222, 'learning_rate': 0.17278355877324048, 'max_depth': 10, 'min_child_weight': 2, 'subsample': 0.9359612747459568, 'colsample_bytree': 0.5107896148605203, 'reg_alpha': 0.0004245871272536665, 'reg_lambda': 1.3794875672794455}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:08:55,665] Trial 45 finished with value: 0.8646616490397788 and parameters: {'regressor': 'XGBoost', 'n_estimators': 202, 'learning_rate': 0.18332151499551114, 'max_depth': 10, 'min_child_weight': 2, 'subsample': 0.9207573200631515, 'colsample_bytree': 0.5052238691608657, 'reg_alpha': 0.0006893014959852092, 'reg_lambda': 1.3825244998889437}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:03,472] Trial 46 finished with value: 0.8548646718047217 and parameters: {'regressor': 'GradientBoostingRegressor', 'n_estimators': 210, 'learning_rate': 0.17092498338381834, 'max_depth': 13, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:05,346] Trial 47 finished with value: 0.8647535484260724 and parameters: {'regressor': 'XGBoost', 'n_estimators': 232, 'learning_rate': 0.1764149251405963, 'max_depth': 11, 'min_child_weight': 2, 'subsample': 0.930136853600882, 'colsample_bytree': 0.5057954957862865, 'reg_alpha': 0.01902412325830144, 'reg_lambda': 1.5508085265320335}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:06,214] Trial 48 finished with value: 0.8629978281775452 and parameters: {'regressor': 'XGBoost', 'n_estimators': 111, 'learning_rate': 0.12739987402896047, 'max_depth': 11, 'min_child_weight': 2, 'subsample': 0.9302221096296118, 'colsample_bytree': 0.5015842299681714, 'reg_alpha': 0.04248946690210555, 'reg_lambda': 2.2163469702369505}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:07,793] Trial 49 finished with value: 0.7419196352021266 and parameters: {'regressor': 'SVR', 'c': 0.12944061299884752, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:13,040] Trial 50 finished with value: 0.7637087970188707 and parameters: {'regressor': 'RandomForest', 'n_estimators': 209, 'max_depth': 12, 'min_samples_split': 8, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:14,027] Trial 51 finished with value: 0.8645795012082452 and parameters: {'regressor': 'XGBoost', 'n_estimators': 112, 'learning_rate': 0.1426509845009108, 'max_depth': 11, 'min_child_weight': 2, 'subsample': 0.9304936639205168, 'colsample_bytree': 0.5023518997052799, 'reg_alpha': 0.07112427675051555, 'reg_lambda': 1.9240546481475111}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:15,931] Trial 52 finished with value: 0.8667023659625878 and parameters: {'regressor': 'XGBoost', 'n_estimators': 249, 'learning_rate': 0.1606570783981964, 'max_depth': 11, 'min_child_weight': 2, 'subsample': 0.930269355506865, 'colsample_bytree': 0.5373958489460795, 'reg_alpha': 0.09861206673947766, 'reg_lambda': 2.6322346048860394}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:17,652] Trial 53 finished with value: 0.8669288706425186 and parameters: {'regressor': 'XGBoost', 'n_estimators': 182, 'learning_rate': 0.1541467106539447, 'max_depth': 11, 'min_child_weight': 1, 'subsample': 0.931814530139892, 'colsample_bytree': 0.5533241574528457, 'reg_alpha': 0.12529264222544859, 'reg_lambda': 8.537132998051904}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:19,187] Trial 54 finished with value: 0.8621477320453894 and parameters: {'regressor': 'XGBoost', 'n_estimators': 245, 'learning_rate': 0.28834981560843853, 'max_depth': 11, 'min_child_weight': 1, 'subsample': 0.8848465968732393, 'colsample_bytree': 0.5507666671730236, 'reg_alpha': 0.38629806444465925, 'reg_lambda': 9.044959225513097}. Best is trial 32 with value: 0.8670140383070929.
[I 2026-07-25 12:09:20,645] Trial 55 finished with value: 0.8673308504775202 and parameters: {'regressor': 'XGBoost', 'n_estimators': 181, 'learning_rate': 0.1168208756464251, 'max_depth': 11, 'min_child_weight': 2, 'subsample': 0.9382715190311158, 'colsample_bytree': 0.5575818995286613, 'reg_alpha': 0.38008792629310245, 'reg_lambda': 3.450020203361082}. Best is trial 55 with value: 0.8673308504775202.
[I 2026-07-25 12:09:21,902] Trial 56 finished with value: 0.865594126962883 and parameters: {'regressor': 'XGBoost', 'n_estimators': 173, 'learning_rate': 0.06750403338069563, 'max_depth': 11, 'min_child_weight': 1, 'subsample': 0.948777321936059, 'colsample_bytree': 0.5668444171710166, 'reg_alpha': 0.6847428347500675, 'reg_lambda': 0.24986498321312928}. Best is trial 55 with value: 0.8673308504775202.
[I 2026-07-25 12:09:28,530] Trial 57 finished with value: 0.8470883479271066 and parameters: {'regressor': 'GradientBoostingRegressor', 'n_estimators': 183, 'learning_rate': 0.06422378505704769, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 55 with value: 0.8673308504775202.

In [236]:
print("Best trial parameters:", study.best_trial.params)
print("Best trial accuracy:", study.best_trial.value)

Best trial parameters: {'regressor': 'XGBoost', 'n_estimators': 401, 'learning_rate': 0.07476401763106098, 'max_depth': 12, 'min_child_weight': 1, 'subsample': 0.6562107391220474, 'colsample_bytree': 0.5924209511158179, 'reg_alpha': 0.009318841159975961, 'reg_lambda': 5.032005021362352}
Best trial accuracy: 0.8705899233167136

In [31]:
#best_params = study.best_params.copy()
#best_params.pop("regressor", None)
from xgboost import XGBRegressor
best_params = {'n_estimators': 401, 'learning_rate': 0.07476401763106098, 'max_depth': 12, 'min_child_weight': 1,
               'subsample': 0.6562107391220474, 'colsample_bytree': 0.5924209511158179, 'reg_alpha': 0.009318841159975961,
               'reg_lambda': 5.032005021362352}


xgb_pipeline = Pipeline(steps=[
                       ('preprocessing',preprocessing),
                       ('regression',XGBRegressor(**best_params))
])

In [32]:
xgb_pipeline.fit(x_train, y_train)

xgb_pred_test = xgb_pipeline.predict(x_test)
xgb_pred_train = xgb_pipeline.predict(x_train)

testing_accuracy = r2_score(y_test,xgb_pred_test)
traning_accuracy = r2_score(y_train,xgb_pred_train)
mae_score = mean_absolute_error(y_test, xgb_pred_test)

print(f"Accuracy of Training {traning_accuracy}")
print(f"Accuracy of Testing {testing_accuracy}")
print(f'MAE {mae_score}')

Accuracy of Training 0.9995366447486227
Accuracy of Testing 0.8999382762853919
MAE 0.29980373004733507

In [33]:
# cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(xgb_pipeline, x_train, y_train, cv=5, scoring='r2').mean()

np.float64(0.880588122020112)

In [34]:
import joblib

joblib.dump(xgb_pipeline, 'Mental_Health_Model.pkl')

['Mental_Health_Model.pkl']

In [12]:
df['Stress_Level'].unique()

array(['Medium', 'Low', 'Very High', 'High'], dtype=object)

In [14]:
from sklearn.model_selection import train_test_split

In [1]:
import sklearn
print("Sklearn version:", sklearn.__version__)

Sklearn version: 1.9.0

In [52]:
pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in d:\users\cccc\anaconda3\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.10.0 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.4.0 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: narwhals>=2.0.1 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in d:\users\cccc\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [36]:
user_input = pd.DataFrame([{
        "Age": 17,
          "Gender": "Male",
          "Country": "Other",
          "Academic_Level": "Undergraduate",
          "Most_Used_Platform": "Facebook",
          "Purpose_Of_Use": "Networking",
          "Avg_Daily_Usage_Hours": 6,
          "Daily_Unlocks": 50,
          "Study_Hours": 4,
          "Physical_Activity_Hours": 1,
          "Sleep_Hours_Per_Night": 8,
          "Stress_Level": "Medium"
    }])

In [63]:
prediction = xgb_pipeline.predict(user_input)[0]

In [65]:
float(prediction)

7.189245223999023

In [46]:
from fastapi.responses import JSONResponse

In [49]:
rest = JSONResponse(status_code=200, content={'response': float(prediction)})

In [56]:
np.asarray(rest).flatten()

array([<starlette.responses.JSONResponse object at 0x000002311D2D1A90>],
      dtype=object)